In [1]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int64

int32


In [2]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype == np.float64)  # Output: True

True


In [3]:
arr = np.array([1+2j, 3-4j, 5j], dtype=np.complex128)
print(arr)


[1.+2.j 3.-4.j 0.+5.j]


In [4]:
arr = np.array([1, 2, 3])
arr_float32 = arr.astype(np.float32)
print(arr_float32.dtype)  # Output: float32

float32


In [5]:
arr = np.array([1.123456, 2.345678], dtype=np.float64)
arr_float32 = arr.astype(np.float32)
print(arr_float32)

[1.123456 2.345678]


In [8]:
def array_attributes(arr):
    print("Shape:", arr.shape)
    print("Size:", arr.size)
    print("Data type:", arr.dtype) 

In [7]:
def array_dimension(arr):
    return arr.ndim

In [9]:
def item_size_info(arr):
    print("Item size:", arr.itemsize)
    print("Total size in bytes:", arr.size * arr.itemsize)

In [10]:
def array_strides(arr):
    print("Strides:", arr.strides)

In [11]:
def shape_stride_relationship(arr):
    print("Shape:", arr.shape)
    print("Strides:", arr.strides)

In [12]:
def create_zeros_array(n):
    return np.zeros(n)

In [13]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

In [14]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

In [15]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

In [16]:
def create_identity_matrix(n):
    return np.eye(n)

In [17]:
def list_to_array(lst):
    return np.array(lst)

In [18]:
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()  # Creates a new view of the same data
view_arr[0] = 10  # Modifies the original array
print(arr)  # Output: [10  2  3  4  5]

[10  2  3  4  5]


In [19]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis):
  return np.concatenate((arr1, arr2), axis=axis)

In [20]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [21]:
def vertical_stack(arrays):
  return np.vstack(arrays)

In [22]:
def create_integer_range(start, end, step):
  return np.arange(start, end+1, step)

In [23]:
def generate_equally_spaced_values(start, end, num):
  return np.linspace(start, end, num)

In [24]:
def generate_logarithmically_spaced_values(start, end, num):
  return np.logspace(np.log10(start), np.log10(end), num)

In [25]:
import pandas as pd

np.random.seed(42)
arr = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df)

<ipython-input-25-d2543bef09e1>:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


    A   B    C
0  52  93   15
1  72  61   21
2  83  87   75
3  75  88  100
4  24   3   22


In [26]:
def replace_negative_values(df, column_name):
  df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])

In [27]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])  # Output: 30

30


In [28]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1, 2])  # Output: 6

6


In [29]:
arr = np.array([3, 8, 2, 10, 5, 7])
result = arr[arr > 5]
print(result)  # Output: [ 8 10  7]

[ 8 10  7]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = arr[2:6]
print(result)  # Output: [3 4 5 6]

[3 4 5 6]


In [31]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr_2d[1:3, 1:3]
print(result)  # Output: [[5 6]
                 #        [8 9]]

[[5 6]
 [8 9]]


In [32]:
def extract_elements(arr, indices):
  return arr[indices]

In [33]:
def filter_elements(arr, threshold):
  return arr[arr > threshold]

In [34]:
def extract_3d_elements(arr, indices1, indices2, indices3):
  return arr[indices1, indices2, indices3]

In [35]:
def filter_multiple_conditions(arr, condition1, condition2):
  return arr[(condition1) & (condition2)]

In [36]:
def extract_elements_by_indices(arr, row_indices, col_indices):
  return arr[row_indices, col_indices]

In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr += 5
print(arr)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [38]:
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = arr1 * arr2
print(result)

[[ 2  6 12]
 [ 8 15 24]
 [14 24 36]]


In [39]:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
result = arr1 + arr2
print(result)

<class 'ValueError'>: operands could not be broadcast together with shapes (1,4) (4,3) 

In [40]:
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [41]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1, 2], [3, 4]])
result = arr1[:, np.newaxis] * arr2
print(result)

<class 'ValueError'>: operands could not be broadcast together with shapes (2,1,3) (2,2) 

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
col_mean = np.mean(arr, axis=0)
print(col_mean)

[2.5 3.5 4.5]


In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print(row_max)

[3 6]


In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
col_max_indices = np.argmax(arr, axis=0)
print(col_max_indices)

[1 1 1]


In [45]:
def moving_sum(arr, window_size):
  return np.cumsum(arr, axis=1)[:, window_size-1:]

arr = np.array([[1, 2, 3], [4, 5, 6]])
result = moving_sum(arr, 2)
print(result)

[[ 3  6]
 [ 9 15]]


In [46]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even_cols = np.all(arr % 2 == 0, axis=0)
print(all_even_cols)

[False False False]


In [47]:
def reshape_array(arr, m, n):
  return arr.reshape(m, n)

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = reshape_array(original_array, 2, 3)
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [48]:
def flatten_matrix(matrix):
  return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


In [49]:
def concatenate_arrays(array1, array2, axis):
  return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenated_array = concatenate_arrays(array1, array2, axis=1)
print(concatenated_array)

[[1 2 5 6]
 [3 4 7 8]]


In [50]:
def split_array(arr, axis, sections):
  return np.split(arr, sections, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_arrays = split_array(original_array, axis=0, sections=3)
print(split_arrays)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [51]:
def insert_and_delete(arr, insert_indices, insert_values, delete_indices):
  arr = np.insert(arr, insert_indices, insert_values)
  arr = np.delete(arr, delete_indices)
  return arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
result_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)

[ 1 10  4 11  5]


In [52]:
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
result = arr1 + arr2
print(result)

[ 6  4 11 10  7]


In [53]:
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print(result)

[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [54]:
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
result = arr1 * arr2
print(result)

[ 5  2 18 36  5]


In [55]:
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2
print(result)

[2. 2. 2. 2. 2.]


In [56]:
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result = arr1 ** arr2
print(result)

[ 1 16 27 16  5]


In [57]:
def count_substring_occurrences(arr, substring):
  return np.char.count(arr, substring).sum()

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
count = count_substring_occurrences(arr, 'hello')
print(count)

3


In [58]:
def extract_uppercase(arr):
  return np.char.upper(arr)

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_arr = extract_uppercase(arr)
print(uppercase_arr)

['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [59]:
def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace_substring(arr, 'apple', 'orange')
print(new_arr)

['orange' 'banana' 'grape' 'pineorange']


In [60]:
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
concatenated_arr = concatenate_strings(arr1, arr2)
print(concatenated_arr)

['HelloOpen' 'WorldAI']


In [61]:
def longest_string(arr):
    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = longest_string(arr)
print(longest_length)

9


In [62]:
data = np.random.randint(1, 1001, 100)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)
print(mean, median, variance, std_dev)

511.24 507.0 85785.30239999999 292.89128085349347


In [63]:
data = np.random.randint(1, 101, 50)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print(percentile_25, percentile_75)

24.0 78.75


In [64]:
x = np.random.randn(100)
y = 2 * x + np.random.randn(100)
corr_coef = np.corrcoef(x, y)[0, 1]
print(corr_coef)

0.8574410909421978


In [65]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
print(product)

[[19 22]
 [43 50]]


In [66]:
data = np.random.randint(10, 1001, 50)
percentile_10 = np.percentile(data, 10)
median = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
print(percentile_10, median, percentile_90, q1, q3)

121.50000000000001 559.5 907.5 329.5 756.75


In [67]:
arr = np.array([10, 20, 30, 40, 50])
index = np.where(arr == 30)[0][0]
print(index)

2


In [68]:
arr = np.random.randint(1, 10, 10)
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 1 2 3 3 4 4 5 8 9]


In [69]:
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_arr = arr[arr > 20]
print(filtered_arr)

[25 42 30]


In [70]:
arr = np.array([1, 5, 8, 12, 15])
filtered_arr = arr[arr % 3 == 0]
print(filtered_arr)

[12 15]


In [71]:
arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]
print(filtered_arr)

[20 30 40]


In [72]:
import numpy as np

arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print(byte_order)  # Output: '<' or '>' depending on the system

=


In [73]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)
print(arr)

[16777216 33554432 50331648]


In [74]:
arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.newbyteorder()
print(new_arr)

[16777216 33554432 50331648]


In [75]:
arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.newbyteorder('>') if arr.dtype.byteorder == '<' else arr
print(new_arr)

[1 2 3]


In [76]:
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '<':
    print("Byte swapping is necessary")
else:
    print("Byte swapping is not necessary")

Byte swapping is not necessary


In [77]:
arr1 = np.array([1, 2, 3, 4, 5])
copy_arr = arr1.copy()
copy_arr[0] = 10
print(arr1)  # Original array remains unchanged

[1 2 3 4 5]


In [78]:
matrix = np.random.randint(1, 10, (3, 3))
view_slice = matrix[1:, 1:]
view_slice[0, 0] = 99
print(matrix)  # Original matrix is modified

[[ 7  8  7]
 [ 5 99  7]
 [ 7  9  3]]


In [79]:
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[1:]
view_b += 5
print(array_a)  # Original array is modified

[[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [80]:
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 99
print(orig_array)  # Original array is modified

[[99  2  3  4]
 [ 5  6  7  8]]


In [81]:
data = np.random.randint(1, 10, (3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 100
print(data)  # Original data remains unchanged

[[9 1 1 4]
 [9 6 3 1]
 [4 9 3 9]]


In [82]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
sum_matrix = A + B
diff_matrix = A - B
print(sum_matrix)
print(diff_matrix)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [83]:
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
product_matrix = np.dot(C, D)
print(product_matrix)

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [84]:
E = np.array([[1, 2, 3], [4, 5, 6]])
transpose_E = E.T
print(transpose_E)

[[1 4]
 [2 5]
 [3 6]]


In [85]:
F = np.array([[1, 2], [3, 4]])
det_F = np.linalg.det(F)
print(det_F)

-2.0000000000000004
